<<<<<<< HEAD
=======
# Generated by Django 3.2 on 2023-05-14 09:20

>>>>>>> 558b520 (подготовлен файл для импорта в базу из csv файлов)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
